# Generated by Django 4.2.1 on 2023-06-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.FloatField(help_text='in minutes')),
                ('ingredients', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('favorites', models.BooleanField()),
            ],
        ),
    ]
