# Generated by Django 4.2.1 on 2023-06-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipes_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.FloatField(help_text='in minutes')),
                ('ingredients', models.CharField(max_length=350)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
